
version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      WEB_PORT: ${WEB_PORT}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:16-alpine
    container_name: appdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
